CREATE DATABASE IF NOT EXISTS tododb;

USE tododb;

CREATE TABLE IF NOT EXISTS todo (
  id INT(11) NOT NULL AUTO_INCREMENT,
  priority TINYINT(10) DEFAULT 0,
  desc VARCHAR(255) NOT NULL,
  complete BOOL DEFAULT 0 ,
  PRIMARY KEY (id)
);

  myDate DATE DEFAULT CURRENT_DATE(),
